---
# Zmienne dla master nodes

k3s_role: master

# Argumenty dla K3s server
k3s_server_args:
  - "--disable=traefik"       # zainstalujemy własnego traefika
  - "--disable=servicelb"     # użyjemy NodePort
  - "--write-kubeconfig-mode=644"
  - "--tls-san={{ k3s_master_ip }}"
