---
all:
  children:
    production:
      hosts:
        docker-01:
          ansible_host: 192.168.40.50
          ansible_user: rocky

    learning:
      hosts:
        rocky-lab-01:
          ansible_host: 192.168.40.100
          ansible_user: rocky
        rocky-lab-02:
          ansible_host: 192.168.40.101
          ansible_user: rocky

  vars:
    ansible_python_interpreter: /usr/bin/python3
