---
# Default variables for k3s-master role

k3s_version: "v1.29.0+k3s1"
k3s_install_script_url: "https://get.k3s.io"

k3s_server_args:
  - "--disable=traefik"
  - "--disable=servicelb"
  - "--write-kubeconfig-mode=644"
